les_polypodes_app_baikal:
    resource: "@LesPolypodesAppBundle/Resources/config/routingBaikal.yml"
    prefix:   /baikal

les_polypodes_app_calserv:
    resource: "@LesPolypodesApp2Bundle/Resources/config/routingCalserv.yml"
    prefix:   /calserv