# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    cal_dav_client:
         class: LesPolypodes\AppBundle\Service\CalDAV\SimpleCalDAVClient
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
