les_polypodes_app_index:
    path:     /
    defaults: { _controller: LesPolypodesAppBundle:Events:index }

les_polypodes_app_create:
    path:     /events/create
    defaults: { _controller: LesPolypodesAppBundle:Events:create }

les_polypodes_app_read:
    path:     /events/view/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:read }

les_polypodes_app_update:
    path:     /events/update/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:update }

les_polypodes_app_delete:
    path:     /events/delete/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:delete }

les_polypodes_app_list:
    path:     /events
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcList }

les_polypodes_app_sabre_list:
    path:     /sabre/events
    defaults: { _controller: LesPolypodesAppBundle:Events:sabreList }

les_polypodes_app_list_event:
    path:     /events/{name}
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcListEvent }

les_polypodes_app_sabre_list_event:
    path:     /sabre/events/{name}
    defaults: { _controller: LesPolypodesAppBundle:Events:sabreListEvent }

les_polypodes_app_form:
    path:     /events/form/
    defaults: { _controller: LesPolypodesAppBundle:Events:form }