les_polypodes_app_index:
    path:     /
    defaults: { _controller: LesPolypodesAppBundle:Events:index, serv: baikal }

les_polypodes_app_create:
    path:     /events/create
    defaults: { _controller: LesPolypodesAppBundle:Events:create, serv: baikal }

les_polypodes_app_update:
    path:     /events/update/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:update, serv: baikal }

les_polypodes_app_delete:
    path:     /events/delete/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:delete, serv: baikal }

les_polypodes_app_list:
    path:     /events
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcList, serv: baikal }

les_polypodes_app_list_event:
    path:     /events/{name}
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcListEvent, serv: baikal }

les_polypodes_app_list_event_raw:
    path:     /events/raw/{name}
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcListEventRaw, serv: baikal }

les_polypodes_app_form:
    path:     /events/form/
    defaults: { _controller: LesPolypodesAppBundle:Events:form, serv: baikal }

les_polypodes_app_dev_insert:
    path:     /dev/insert/{name}/{n}/{type}
    defaults: { _controller: LesPolypodesAppBundle:Events:devInsert, n: 1, type: standard, serv: baikal}
    requirements:
        n: \d+

les_polypodes_app_test:
    path:     /test
    defaults: { _controller: LesPolypodesAppBundle:Events:test }