les_polypodes_app_index:
    path:     /
    defaults: { _controller: LesPolypodesAppBundle:Events:index }

les_polypodes_app_create:
    path:     /events/create
    defaults: { _controller: LesPolypodesAppBundle:Events:create }

les_polypodes_app_read:
    path:     /events/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:read }

les_polypodes_app_update:
    path:     /events/update/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:update }

les_polypodes_app_delete:
    path:     /events/delete/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:delete }

les_polypodes_app_list:
    path:     /events
    defaults: { _controller: LesPolypodesAppBundle:Events:list }

les_polypodes_app_sabre_list:
    path:     /sabre/events
    defaults: { _controller: LesPolypodesAppBundle:Events:sabreList }
