les_polypodes_app_index:
    path:     /{serverName}
    defaults: { _controller: LesPolypodesAppBundle:Events:index, serverName: baikal }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_create:
    path:     /{serverName}/events/create
    defaults: { _controller: LesPolypodesAppBundle:Events:create, serverName: baikal }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_update:
    path:     /{serverName}/events/update/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:update, serverName: baikal }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_delete_all:
    path:     /{serverName}/events/delete/all/{calendarName}
    defaults: { _controller: LesPolypodesAppBundle:Events:deleteAll, serverName: baikal }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_delete:
    path:     /{serverName}/events/delete/{calendarName}/{id}
    defaults: { _controller: LesPolypodesAppBundle:Events:delete, serverName: baikal }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_list:
    path:     /{serverName}/events
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcList, serverName: baikal }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_list_event_raw:
    path:     /{serverName}/events/raw/{calendarName}
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcListEventRaw, serverName: baikal, start: null, end: null }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_list_event:
    path:     /{serverName}/events/{calendarName}
    defaults: { _controller: LesPolypodesAppBundle:Events:scdcListEvent, serverName: baikal, start: null, end: null }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_form:
    path:     /{serverName}/events/form/
    defaults: { _controller: LesPolypodesAppBundle:Events:form, serverName: baikal }
    requirements:
        serverName: baikal|calserv

les_polypodes_app_dev_insert:
    path:     /{serverName}/dev/insert/{calendarName}/{n}/{type}
    defaults: { _controller: LesPolypodesAppBundle:Events:devInsert, n: 1, type: standard, serverName: baikal}
    requirements:
        n: \d+
        serverName: baikal|calserv