services:
#    les_polypodes_app.example:
#        class: LesPolypodes\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    calDAVClientProvider:
        class: "LesPolypodes\AppBundle\Services\CalDAVClientProvider"
        calls:
            - [ setContainer,[ @service_container ] ]
    vCalProvider:
        class: "LesPolypodes\AppBundle\Services\VCalProvider"
        calls:
            - [ setContainer,[ @service_container ] ]